plugins {
    id 'com.android.application'
}
android {
    namespace 'com.example.vault'
    compileSdk 33
    defaultConfig {
        applicationId "com.example.vault"
        minSdk 24
        targetSdk 33
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        useLibrary 'org.apache.http.legacy'
    }


    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES']
        }
    }


    lint {
        abortOnError false
        checkReleaseBuilds false
    }

}

configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetai
